RPG/RPG/Pages/Achievements.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RPG.Service;
using RPG.Model;

namespace RPG
{
    public class AchievementsModel : PageModel
    {
        readonly RpgLogic _rpgLogic;
        public User Stats { get; set; }
        public AchievementsModel(RpgLogic rpgLogic)
        {
            _rpgLogic = rpgLogic;
        }

        public void OnGet()
        {
            Stats = _rpgLogic.Stats;
        }
    }
}

RPG/RPG/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RPG.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RPG/RPG/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using RPG.Model;
using RPG.Service;

namespace RPG.Pages
{
    public class IndexModel : PageModel
    {
        readonly SessionStorage _session;

        public User Stats { get; set; }

        public IndexModel(SessionStorage session)
        {
            _session = session;
        }

        public void OnGet()
        {
            Stats = new User();
            _session.SaveStats(Stats);
        }
    }
}

RPG/RPG/Pages/Location.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RPG.Service;
using RPG.Model;

namespace RPG.Pages
{
    public class LocationModel : PageModel
    {
        readonly RpgLogic _rpgLogic;

        public Location location { get; set; }
        public User Stats { get; set; }

        public LocationModel(RpgLogic rpgLogic)
        {
            _rpgLogic = rpgLogic;
        }

        public void OnGet(int path)
        {
            Stats = _rpgLogic.Stats;
            location = _rpgLogic.Play(path);
        }

        public void OnGetSleep()
        {
            location = _rpgLogic.Sleep();
            Stats = _rpgLogic.Stats;
        }

        public void OnGetSearchFood()
        {
            location = _rpgLogic.SearchFood();
            Stats = _rpgLogic.Stats;
        }

    }
}

RPG/RPG/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RPG.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RPG/RPG/Pages/Story.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RPG
{
    public class StoryModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

RPG/RPG/Pages/Achievements.cshtml
@page
@model RPG.AchievementsModel
@using RPG.Model
@{
    ViewData["Title"] = "Achievements";
}

<h1>Achievements</h1>
<ul>
    @foreach (var a in Model.Stats.Achievements)
    {
        <li>@a.Name - @a.Description</li>
    }

</ul>
<p><a asp-page="/location">ZPĚT</a></p>

RPG/RPG/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    <div class="text-center">
        <h1 class="display-4">RPG</h1>
        <p>Stiskni <a asp-page="/story">ZAČÍT HRÁT</a> aby jsi spustil hru.</p>
    </div>

RPG/RPG/Pages/Location.cshtml
@page
@model RPG.Pages.LocationModel
@using RPG.Model
@{
    ViewData["Title"] = "Location";
}

    <div class="text-center">
        @if (Model.location.Achievement != null)
        {
            <p>Získán nový úspěch - @Model.location.Achievement.Name (@Model.location.Achievement.Description)</p>
            <hr />
        }



        <h1 class="display-4">@Model.location.Name</h1>
        <p>@Model.location.Description</p>

        <hr />

        @foreach (var path in Model.location.Paths)
        {
            <p><a asp-page="/location" asp-route-path="@path.NextLocationId">@path.Description</a></p>
        }

        @if (Model.location.CanSearchFood)
        {
            <p><a asp-page="/location" asp-page-handler="SearchFood">Hledat jídlo</a></p>
        }
        @if (Model.location.CanSleep)
        {
            <p><a asp-page="/location" asp-page-handler="Sleep">Vyspat se</a></p>
        }

        <hr />

        @if (Model.location.ShowStats)
        {
            <h2>Tvé statistiky:</h2>
            <p>Jídlo: @Model.Stats.Food%</p>
            <p>Energie: @Model.Stats.Energy%</p>
        }

    </div>

RPG/RPG/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RPG</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RPG</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Achievements">Úspěchy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RPG - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

RPG/RPG/Pages/Story.cshtml
@page
@model RPG.StoryModel
@{
    ViewData["Title"] = "Story";
}

<h1>Story</h1>
<div class="text-center">
    <h1 class="display-4">Příběh</h1>
    <p class="font-italic">
        Nácházíš se na opuštěném ostrově, protože tvému soukromému triskáči přestaly fungovat motory, ale naštěstí jsi měl padák.

        Spadl jsi do moře a plaval jsi půl dne, než jsi se dostal na tento ostrov a proto si vyčerpaný. Máš u sebe pouze mobilní telefon a hodinky.
        Tvým úkolem je nasbírat co nejvíce <a asp-page="/achievements">ÚSPĚCHŮ</a> a dostat se z ostrova.
        Gl...
    </p>
</div>
<div class="text-left">
    <p><a asp-page="/location">Pokračovat</a></p>

</div>